name: ci

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Auto green
        run: |
          git config --local user.email "billzhou233@yandex.com"
          git config --local user.name "uni-31356"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          date +"%Y-%m-%d %H:%M:%S.%N" > keepchange.txt
          git commit -am "jaja"
          git push
